
[shell]
# program = "/opt/homebrew/bin/tmux"
program = "/bin/zsh"
args = ["-l"]
# args = ["-- -l", "--command", "tmux new-session -A -D -s main"]
# args = ["-l", "-c", "tmux attach || tmux"]

[cursor]
style = "Beam"

[font]
size = 19.0
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }

[window]
startup_mode = "Maximized"
dynamic_padding = true
opacity = 0.85
blur = true

[window.padding]
x = 6
y = 0

# Number of lines/columns (not pixels) in the terminal.
[window.dimensions]
columns = 110
lines = 45

# Colors (Everforest Light)

# Default colors
[colors.primary]
background = '#fdf6e3'
foreground = '#5c6a72'

# Normal colors
[colors.normal]
black = '#5c6a72'
red = '#f85552'
green = '#8da101'
yellow = '#dfa000'
blue = '#3a94c5'
magenta = '#df69ba'
cyan = '#35a77c'
white = '#e0dcc7'

# Bright Colors
[colors.bright]
black = '#5c6a72'
red = '#f85552'
green = '#8da101'
yellow = '#dfa000'
blue = '#3a94c5'
magenta = '#df69ba'
cyan = '#35a77c'
white = '#e0dcc7'

[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[keyboard]
bindings = [
  { key = "V", mods = "Command", action = "Paste" },
  { key = "C", mods = "Command", action = "Copy" },
  { key = "Q", mods = "Command", action = "copy" },
  { key = "N", mods = "Command", action = "SpawnNewInstance" },
  # { key = "I", mods = "Control", chars = "\\x1b[105;5u" }
# { key = "W", mods = "Command", chars = "\x02&"}, #close tmux tab
  # { key = "T", mods = "Command", chars = "\x02c"}, #create new tmux tab
]
